### ISSUE TITLE
CalculationAPI needs to be rewritten

### ISSUE THREAD

**Issue by EpicSharpCode** [GingerBreadMuncher/GingerBreadCalc#3]
The **CalculationAPI** needs to be rewritten to separate it from the output functions. The results should be obtained by calling CalcFunctions using the **return** values.
![image](https://github.com/GingerBreadMuncher/GingerBreadCalc/assets/109740243/ca09b21b-2ac8-46b5-9f61-b974151b8b43)

**Comment by GingerBreadMuncher** [comment]
This issue has been adressed by [46d1c79] commit.

**Comment by EpicSharpCode** [comment]
Great job! 🎉
